# Generated by Django 4.1.3 on 2023-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_profile_userposition_remove_user_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='looking_for_job',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('LOOKING FOR JOB', 'Looking for job'), ('CUSTOMER', 'Customer'), ('HAVE JOB', 'Have job')], default='CUSTOMER', max_length=15),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='type_of_activity',
            field=models.CharField(choices=[('INDIVIDUAL ENTREPRENEUR', 'Individual entrepreneur'), ('COMPANY PERSONNEL', 'Company personnel')], default='INDIVIDUAL ENTREPRENEUR', max_length=23),
        ),
    ]
