# Generated by Django 4.1.3 on 2022-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('SALES MANAGER', 'Менеджер по продажам'), ('SELF EMPLOYED', 'Самозанятый'), ('RESELLER', 'Перекуп')], default=None, max_length=15, null=True),
        ),
    ]
