# Generated by Django 4.1.3 on 2022-12-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_status',
            new_name='employee_position',
        ),
    ]
