# Generated by Django 4.1.3 on 2023-01-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usersapp', '0004_remove_profile_status_employeeposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeposition',
            name='position_category',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='position_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
