# Generated by Django 4.1.3 on 2022-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='header',
            new_name='title',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
