# Generated by Django 4.1.3 on 2022-12-27 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(help_text="Choose category of your Company. If it's not in the list just write it down and it will be created in our Data Base for future uses", null=True, on_delete=django.db.models.deletion.PROTECT, to='marketapp.companycategory'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='category',
            field=models.ForeignKey(help_text="Choose category of your Advertisment. If it's not in the list just write it down and it will be created in our Data Base for future uses", null=True, on_delete=django.db.models.deletion.PROTECT, to='marketapp.advertcategory'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.company', to_field='slug'),
        ),
    ]
