# Generated by Django 4.1.3 on 2022-12-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='company',
        ),
    ]
