# Generated by Django 4.1.3 on 2022-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
