# Generated by Django 4.1.3 on 2022-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('GOODS', 'Товары'), ('SERVICES', 'Услуги'), ('VACANCY', 'Вакансия'), ('<django.db.models.fields.SlugField>', 'Slug')], default='GOODS', max_length=40),
        ),
    ]
