# Generated by Django 4.1.3 on 2022-12-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_remove_feedback_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='user',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.company'),
        ),
    ]
