# Generated by Django 4.1.3 on 2022-11-26 17:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from=('category', 'title'), unique_with=('title',), verbose_name='URL'),
        ),
    ]
