# Generated by Django 4.1.3 on 2022-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('GOODS', 'Товары'), ('SERVICES', 'Услуги'), ('VACANCY', 'Вакансия')], default='GOODS', max_length=40),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='URL'),
        ),
    ]
