# Generated by Django 4.1.3 on 2022-12-10 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketapp', '0003_remove_advertisment_user_advertisment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
