# Generated by Django 4.1.3 on 2022-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_advertisment_rating_alter_company_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='star_given',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Five'), (4, 'Four'), (3, 'Three'), (2, 'Two'), (1, 'One')], default=1),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
