# Generated by Django 4.1.3 on 2022-12-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_feedback_advert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackAdvert',
        ),
    ]
