# Generated by Django 4.1.3 on 2022-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_alter_advertisment_category_alter_advertisment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
