# Generated by Django 4.1.3 on 2022-12-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_alter_company_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.advertisment')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketapp.starrating')),
            ],
        ),
    ]
