# Generated by Django 4.1.3 on 2022-12-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_starrating_advertrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertRating',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='StarRating',
            new_name='Star',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='star_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.rating'),
        ),
    ]
