# Generated by Django 4.1.3 on 2022-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_alter_advertisment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('GOODS', 'Товары'), ('SERVICES', 'Услуги'), ('VACANCY', 'Вакансия')], default='GOODS', max_length=15),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
