# Generated by Django 4.1.3 on 2022-12-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0006_rename_advertrating_rating_rename_starrating_star_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='advert',
        ),
        migrations.CreateModel(
            name='FeedbackAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.advertisment')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.feedback')),
            ],
        ),
    ]
