# Generated by Django 4.1.3 on 2022-12-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_remove_feedback_advert_feedbackadvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='advert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.advertisment'),
        ),
        migrations.DeleteModel(
            name='FeedbackAdvert',
        ),
    ]
