# Generated by Django 4.1.3 on 2022-12-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0007_alter_feedback_advert_company_feedback_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='advert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.advertisment', to_field='slug'),
        ),
    ]
