# Generated by Django 4.1.3 on 2023-01-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('followapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.company'),
        ),
    ]
